packages:
  - apps/*
  - packages/*
  - tools/*

ignoredBuiltDependencies:
  - dtrace-provider

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - msw
  - sharp
  - spawn-sync
